name: Contributors
on:
  push:
    branches:
      - master
jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wow-actions/contributors-list@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          svgPath: CONTRIBUTORS.svg
          sort: true
          round: true
          includeBots: false
          userNameHeight: 19
          # This job does not have commit powers to the `master` branch
          noCommit: true
          itemTemplate: >
            <g transform="translate({{ x }}, {{ y }})">
              <a xlink:href="{{{ url }}}" class="contributor-link" target="_blank" rel="nofollow sponsored" title="{{{ name }}}" id="{{{ name }}}">
                <image width="{{ width }}" height="{{ height }}" xlink:href="{{{ avatar }}}" />
                <text x="32" y="74" text-anchor="middle" alignment-baseline="middle" font-size="10">{{{ name }}}</text>
              </a>
            </g>
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: '[chore] update contributors svg'
          title: '[chore] update contributors svg'
          delete-branch: true
          assignees: gutmensch
          reviewers: gutmensch
